# Generated by Django 6.0.5 on 2026-06-18 12:43

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0234_cablepath_nodes_index'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0089_default_ordering_indexes'),
        ('netbox_routing', '0033_isis'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFDInterface',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('micro_bfd', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BFD Interface',
                'verbose_name_plural': 'BFD Interfaces',
                'ordering': ('interface',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Redistribution',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('destination_id', models.PositiveBigIntegerField()),
                ('source_protocol', models.CharField(max_length=16)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'metric_type',
                    models.CharField(blank=True, default='', max_length=16),
                ),
            ],
            options={
                'verbose_name': 'Redistribution',
                'verbose_name_plural': 'Redistributions',
                'ordering': [
                    'destination_type',
                    'destination_id',
                    'source_protocol',
                    'source_ref',
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RouteMapEntrySetCommunity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('operation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Route Map Set Community',
                'verbose_name_plural': 'Route Map Set Communities',
                'ordering': ('route_map_entry', 'operation', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='bgppeer',
            name='bfd_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitylist',
            name='invert_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='cost',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='network_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routemap',
            name='default_action',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='routemapentry',
            name='apply_policy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='applied_by_entries',
                to='netbox_routing.routemap',
            ),
        ),
        migrations.AddField(
            model_name='routemapentry',
            name='call_policy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='called_by_entries',
                to='netbox_routing.routemap',
            ),
        ),
        migrations.AddField(
            model_name='routemapentry',
            name='match_afi',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name='routemapentry',
            name='match_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routemapentry',
            name='vendor_ext',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community',
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[\\w.:*^$()\\[\\]|+?\\\\-]+$'
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='ospfinstance',
            name='process_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterConstraint(
            model_name='ospfinstance',
            name='netbox_routing_ospfinstance_unique_device_name',
            constraint=models.UniqueConstraint(
                fields=('device', 'name'),
                name='netbox_routing_ospfinstance_unique_device_name',
                nulls_distinct=False,
                violation_error_message=(
                    'Name must be unique per device. '
                    'Only a single empty name is permitted per device.'
                ),
            ),
        ),
        migrations.AddField(
            model_name='bfdinterface',
            name='bfd_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='interfaces',
                to='netbox_routing.bfdprofile',
            ),
        ),
        migrations.AddField(
            model_name='bfdinterface',
            name='interface',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bfd_interface',
                to='dcim.interface',
            ),
        ),
        migrations.AddField(
            model_name='bfdinterface',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='bfdinterface',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='destination_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='users.owner',
            ),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='route_map',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='redistribution_entries',
                to='netbox_routing.routemap',
            ),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='tags',
            field=taggit.managers.TaggableManager(
                through='extras.TaggedItem', to='extras.Tag'
            ),
        ),
        migrations.AddField(
            model_name='routemapentrysetcommunity',
            name='communities',
            field=models.ManyToManyField(
                blank=True,
                related_name='set_by_route_map_entries',
                to='netbox_routing.community',
            ),
        ),
        migrations.AddField(
            model_name='routemapentrysetcommunity',
            name='community_list',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='set_by_route_map_entries',
                to='netbox_routing.communitylist',
            ),
        ),
        migrations.AddField(
            model_name='routemapentrysetcommunity',
            name='route_map_entry',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='set_communities',
                to='netbox_routing.routemapentry',
            ),
        ),
        migrations.AddConstraint(
            model_name='redistribution',
            constraint=models.UniqueConstraint(
                fields=(
                    'destination_type',
                    'destination_id',
                    'source_protocol',
                    'source_ref',
                ),
                name='netbox_routing_redistribution_unique_destination_source',
            ),
        ),
    ]
