# Generated by Django 6.0.5 on 2026-06-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0234_cablepath_nodes_index'),
        ('netbox_routing', '0034_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeer',
            name='update_source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bgp_update_source_peers',
                to='dcim.interface',
            ),
        ),
    ]
