# Generated by Django 6.0.5 on 2026-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0035_bgppeer_update_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isisinstance',
            name='area_auth_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='domain_auth_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='isisinterface',
            name='hello_auth_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='isislevel',
            name='auth_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
