# Generated by Django 6.0.6 on 2026-07-12 07:34

import netbox_routing.fields.ip
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0035_bgppeer_update_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgprouter',
            name='router_id',
            field=netbox_routing.fields.ip.IPAddressField(blank=True, null=True),
        ),
    ]
