# Generated by Django 6.0.5 on 2026-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0036_isis_auth_hmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='isisinstance',
            name='fast_reroute',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='microloop_avoidance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='frr_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='frr_protection',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
