# Generated by Django 6.0.5 on 2026-07-07 19:49

import django.db.models.deletion
import ipam.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_routing', '0037_isis_fast_reroute'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isissegmentrouting',
            name='node_sid_index',
        ),
        migrations.RemoveField(
            model_name='isissegmentrouting',
            name='node_sid_label',
        ),
        migrations.RemoveField(
            model_name='isissegmentrouting',
            name='node_sid_v6_index',
        ),
        migrations.RemoveField(
            model_name='isissegmentrouting',
            name='node_sid_v6_label',
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='ignore_attached_bit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='suppress_attached_bit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='srlb_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='srlb_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isissegmentrouting',
            name='srv6_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ISISPrefixSID',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('algorithm', models.PositiveSmallIntegerField(default=0)),
                ('sid_index', models.PositiveIntegerField(blank=True, null=True)),
                ('sid_label', models.PositiveIntegerField(blank=True, null=True)),
                ('n_flag', models.BooleanField(blank=True, null=True)),
                ('no_php', models.BooleanField(blank=True, null=True)),
                ('explicit_null', models.BooleanField(blank=True, null=True)),
                ('readvertise', models.BooleanField(blank=True, null=True)),
                (
                    'interface',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prefix_sids',
                        to='netbox_routing.isisinterface',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'IS-IS Prefix-SID',
                'ordering': ('interface', 'algorithm'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('interface', 'algorithm'),
                        name='netbox_routing_isisprefixsid_interface_algorithm_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('algorithm', 0),
                            models.Q(('algorithm__gte', 128), ('algorithm__lte', 255)),
                            _connector='OR',
                        ),
                        name='netbox_routing_isisprefixsid_algorithm_range',
                    ),
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ISISSRv6Locator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=64)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('algorithm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_anycast', models.BooleanField(blank=True, null=True)),
                ('is_micro_segment', models.BooleanField(blank=True, null=True)),
                ('flavor', models.CharField(blank=True, default='', max_length=64)),
                (
                    'block_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'node_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'function_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    'argument_length',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('isis_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('vendor_ext', models.JSONField(blank=True, default=dict)),
                (
                    'instance',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='srv6_locators',
                        to='netbox_routing.isisinstance',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='users.owner',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'verbose_name': 'IS-IS SRv6 Locator',
                'ordering': ('instance', 'name'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('instance', 'name'),
                        name='netbox_routing_isissrv6locator_instance_name_unique',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('algorithm', 0),
                            models.Q(('algorithm__gte', 128), ('algorithm__lte', 255)),
                            ('algorithm__isnull', True),
                            _connector='OR',
                        ),
                        name='netbox_routing_isissrv6locator_algorithm_range',
                    ),
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
