# Generated by Django 6.1 on 2026-09-15 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing', '0037_owner_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community',
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        '\\A[\\w.:*^$()\\[\\]|+?\\\\-]+\\Z'
                    )
                ],
            ),
        ),
    ]
