# Generated by Django 6.1 on 2026-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('netbox_routing', '0039_staticroute_device_triple_uniqueness'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aspath',
            name='netbox_routing_aspath_unique_name',
        ),
        migrations.RemoveConstraint(
            model_name='prefixlist',
            name='netbox_routing_prefixlist_unique_name',
        ),
        migrations.RemoveConstraint(
            model_name='routemap',
            name='netbox_routing_routemap_unique_name',
        ),
        migrations.AddConstraint(
            model_name='aspath',
            constraint=models.UniqueConstraint(
                fields=('name',),
                name='netbox_routing_aspath_unique_name',
                violation_error_message='Name must be unique.',
            ),
        ),
        migrations.AddConstraint(
            model_name='prefixlist',
            constraint=models.UniqueConstraint(
                fields=('name',),
                name='netbox_routing_prefixlist_unique_name',
                violation_error_message='Name must be unique.',
            ),
        ),
        migrations.AddConstraint(
            model_name='routemap',
            constraint=models.UniqueConstraint(
                fields=('name',),
                name='netbox_routing_routemap_unique_name',
                violation_error_message='Name must be unique.',
            ),
        ),
    ]
